# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitresume < Formula
  desc "A CLI tool that converts your git commit history into resume-ready bullet points using AI."
  homepage "https://gitresume.app"
  version "0.1.0-SNAPSHOT-1c73efe"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0-SNAPSHOT-1c73efe_darwin_amd64.tar.gz"
      sha256 "e5fdc02c0c8e5d96751e1f98aa01bdd2e61878e1c705a8383972c866202dbd59"

      def install
        bin.install "gitresume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0-SNAPSHOT-1c73efe_darwin_arm64.tar.gz"
      sha256 "f1dd0f8888ccd48922cbdd1e956ad7b8cebd318913a6eaa4d6a2d1f7ded4be75"

      def install
        bin.install "gitresume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0-SNAPSHOT-1c73efe_linux_amd64.tar.gz"
      sha256 "55d968a967d2b6fcb88a48b214e3e9dd23e75bd17624e901cba0e2c9065c111b"
      def install
        bin.install "gitresume"
      end
    end
  end

  test do
    system "#{bin}/gitresume --version"
  end
end
