# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitresume < Formula
  desc "A CLI resume builder that transforms your Git commit history into professional, AI-generated resume bullet points"
  homepage "https://gitresume.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "55cba08379a8b6da5e25753584f983c1607a0d958b57e4b9e75ceee266e2675a"

      def install
        bin.install "gitresume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "e5cfaa0c042e6b5809668fa83da5c22e1197adf2c2d815bdc04716239c8abca8"

      def install
        bin.install "gitresume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "cd08de144428f7f225d0fed67f7c69850a086fe8256f61c0678756735a71dfa6"
      def install
        bin.install "gitresume"
      end
    end
  end

  test do
    system "#{bin}/gitresume --version"
  end
end
