# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitresume < Formula
  desc "A CLI tool that converts your git commit history into resume-ready bullet points using AI."
  homepage "https://gitresume.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "8204cc65e053607204fea7a3c38d053391d2602c429a838b4317201a2bae3b9e"

      def install
        bin.install "gitresume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "b8127a806533423b9005eae05c390864f8f65d6abb7de4edf2800060dff8dff8"

      def install
        bin.install "gitresume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e2aeb58a622fab046a972e097a89187ad1af8d448f0736acec5ca16ca1e8dad9"
      def install
        bin.install "gitresume"
      end
    end
  end

  test do
    system "#{bin}/gitresume --version"
  end
end
