# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitresume < Formula
  desc "A CLI resume builder that transforms your Git commit history into professional, AI-generated resume bullet points"
  homepage "https://gitresume.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "89ca532d5e996d6b295e2ce823510adf074c3eb9781a4c3d49dd9eb013c43d3d"

      def install
        bin.install "gitresume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "8fa730494609c800fe4250622c34f5748f0dcb4a78555a45700f4ec97b886e46"

      def install
        bin.install "gitresume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamhabbeboy/gitresume-cli/releases/download/v0.1.0/gitresume-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "4dbea878dd5707de428f7a2f6bd1ca292b2b3e2c20501e81c603370ed224ccdd"
      def install
        bin.install "gitresume"
      end
    end
  end

  test do
    system "#{bin}/gitresume --version"
  end
end
